// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swsqmsbyikznalrvydny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3c3Ftc2J5aWt6bmFscnZ5ZG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTYxODYsImV4cCI6MjA3OTU5MjE4Nn0.fMBkdy28G5ebXYI0BKvIe9AL7N4d7q_zj5tZoF5m_yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Extend session duration significantly
    refreshTokenRotationEnabled: true,
    // Custom session refresh settings
    sessionRefreshMargin: 60, // Refresh 60 seconds before expiry
    sessionRefreshRetryInterval: 5, // Retry every 5 seconds if refresh fails
  },
  // Global settings
  global: {
    headers: {
      'X-Client-Info': 'pos-system-v1',
    },
  },
});